apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - externalsecret.yaml
  - ingress.yaml

helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.67.0
    namespace: monitoring
    releaseName: vm
    valuesFile: values.yaml
    includeCRDs: true
