apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - clusters.yaml
  - externalsecret.yaml
  - ingress.yaml
  - namespace.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.2.4
    namespace: argocd
    releaseName: argocd
    valuesFile: values.yaml

# patches:
#   - path: argocd-cm.yaml
#   - path: argocd-rbac-cm.yaml
